apiVersion: v1
kind: Service
metadata:
  name: matchfunction
  namespace: dataleague
  labels:
    service: matchfunction
spec:
  selector:
    app: matchfunction
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 50502
